"""empty message

Revision ID: b559b8e2ed43
Revises: caaec57f5dc6
Create Date: 2026-09-09 18:23:22.503372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b559b8e2ed43'
down_revision: Union[str, Sequence[str], None] = 'caaec57f5dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'image_path',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
