"""empty message

Revision ID: caaec57f5dc6
Revises: a5737def44ec
Create Date: 2026-09-08 16:21:33.202170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaec57f5dc6'
down_revision: Union[str, Sequence[str], None] = 'a5737def44ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_path', sa.Text(), nullable=True))
    op.drop_column('comments', 'image_url')
    op.add_column('posts', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_path')
    op.add_column('comments', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'image_path')
    # ### end Alembic commands ###
